# Generated by Django 5.2.9 on 2025-12-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('release_year', models.IntegerField(verbose_name='개봉년도')),
                ('genre', models.CharField(max_length=50, verbose_name='장르')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='별점')),
                ('director', models.CharField(max_length=100, verbose_name='감독')),
                ('main_actor', models.CharField(max_length=200, verbose_name='주연')),
                ('runtime', models.IntegerField(verbose_name='러닝타임(분)')),
                ('review_content', models.TextField(verbose_name='리뷰')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
