# Generated by Django 6.0.1 on 2026-01-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='포스터 경로'),
        ),
        migrations.AddField(
            model_name='review',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='TMDB ID'),
        ),
    ]
