# Generated by Django 6.0.1 on 2026-01-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_poster_path_review_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='포스터 이미지'),
        ),
    ]
