# Generated by Django 4.2.30 on 2026-06-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='감상 태그'),
        ),
    ]
