# Generated by Django 4.2.30 on 2026-06-17 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_add_tags_to_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
    ]
